# Generated by Django 5.2.4 on 2025-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
