# Generated by Django 5.2.4 on 2025-10-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_shareholder_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='laive',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
