# Generated by Django 5.2.4 on 2025-11-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customerdata_laive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='laive',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
